### ISSUE TITLE
HHVM not running after reboot

### ISSUE THREAD

**Issue by shaneholloman** [rtCamp/easyengine#498]
**After rebooting HHVM was not running**

I was watching server page requests in `htop` and noticed HHVM was not firing so I ran this command to force HHVM to start on reboot `sudo update-rc.d hhvm defaults` and rebooted, - all appears well.

**Terminal feedback as follows:**
```
root@fuega:~# sudo update-rc.d hhvm defaults
Adding system startup for /etc/init.d/hhvm ... 
    /etc/rc0.d/K20hhvm -> ../init.d/hhvm 
    /etc/rc1.d/K20hhvm -> ../init.d/hhvm 
    /etc/rc6.d/K20hhvm -> ../init.d/hhvm 
    /etc/rc2.d/S20hhvm -> ../init.d/hhvm 
    /etc/rc3.d/S20hhvm -> ../init.d/hhvm 
    /etc/rc4.d/S20hhvm -> ../init.d/hhvm 
    /etc/rc5.d/S20hhvm -> ../init.d/hhvm
root@fuega:~# reboot
```
I hope this correct. Or maybe this makes HHVM run for all sites if your server has more then one site but only configured HHVM for one in EE

**Question:** So a good question maybe is `sudo update-rc.d hhvm defaults` the correct command to use in conjunction with an EE configured server? 

ref:
```
********************************************************************
* HHVM is installed. Here are some more things you might want to do:
* 
* Configure your webserver to use HHVM:
* $ sudo /usr/share/hhvm/install_fastcgi.sh
* $ sudo /etc/init.d/nginx restart
* $ sudo /etc/init.d/apache restart
* $ sudo /etc/init.d/hhvm restart
* 
* Start HHVM at boot:
* $ sudo update-rc.d hhvm defaults
* 
* Run command line scripts with HHVM:
* $ hhvm whatever.php
* 
* Use HHVM for /usr/bin/php even if you have php-cli installed:
* $ sudo /usr/bin/update-alternatives --install /usr/bin/php php /usr/bin/hhvm 60
********************************************************************
```

**Comment by MiteshShah** [comment]
@shaneholloman 
```
sudo update-rc.d hhvm defaults
```

Above command is correct one to start service when system boot and its kill service when system reboot/shutdown.

> Question: So a good question maybe is sudo update-rc.d hhvm defaults the correct command to use in conjunction with an EE configured server?


@gau1991 @harshadyeola Is there any special handling require for this ?

**Comment by MiteshShah** [comment]
@gau1991 When you fix the issue mention issue number in your commit message so ee users are aware of we are working on this issue/task.

Refer: https://github.com/rtCamp/easyengine/commit/d2542db434fd8a0d59b179f37cb21a0c8138c535

**Comment by gau1991** [comment]
Hello..
This issue is fixed in EasyEngine 3.1.1

**Comment by kangarooo** [comment]
Still not running on clean install
I have not yet put any WP yet cause just installing all system and reading.

Did new cloud server
from root made 2nd user
From 2nd user
ee stack install --all
witch installed different things under ip:22222
sudo ee stack install --hhvm
sudo ee stack install --admin

service hhvm status
* hhvm.service - HHVM PHP/Hack runtime
   Loaded: loaded (/lib/systemd/system/hhvm.service; disabled; vendor preset: en
   Active: inactive (dead)


Isnt it faster if ill make some WP commands when HHVM running? Wont HHVM make WP faster? Do i put also Nginx fastcgi? Will thouse work with caching plugins if execute wp install with some cache plugin? Witch cache plugin is best? I want max performance.

**Comment by ekongbrian** [comment]
This did not work : sudo update-rc.d hhvm defaults
I use this and it works: sudo update-rc.d hhvm enable
