### ISSUE TITLE
dependency problems prevent configuration of mariadb-server on Ubuntu

### ISSUE THREAD

**Issue by ldashdixon** [rtCamp/easyengine#618]
Hey guys, up until yesterday, installs were working perfectly for me on Ubuntu 14.04.  Yesterday, however, a MariaDB update began causing installation issues, effectively breaking site creation on Ubuntu.  Reference:  https://mariadb.com/kb/en/mariadb/mariadb-5533-debian-and-ubuntu-installation-issues/ .  I know this isn't an EasyEngine problem, per se, but perhaps there is a work around that can be integrated for the time being.  Maybe a Percona DB alternative?

**Comment by nikhilgoyal** [comment]
I am also facing the same issue. Getting this.

```
Hit http://mirrors.digitalocean.com trusty-updates/universe Translation-en
Fetched 316 B in 5s (59 B/s)
W: Failed to fetch http://mirror.aarnet.edu.au/pub/MariaDB/repo/10.0/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found [IP: 202.158.214.106 80]

W: Failed to fetch http://mirror.aarnet.edu.au/pub/MariaDB/repo/10.0/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found [IP: 202.158.214.106 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
2015-09-19 05:39:18,207 (INFO) ee : Oops Something went wrong!!
2015-09-19 05:39:18,207 (ERROR) ee : Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
```
on two different servers and multiple DO droplets.

**Comment by colthreepv** [comment]
+1, everyone gets this problem trying to install since is an APT problem..

easy workaround for now is edit `/etc/apt/sources.list.d/ee-repo.list', and replace mariadb repository with [something from here](https://downloads.mariadb.org/mariadb/repositories/#mirror=one&distro=Ubuntu&distro_release=trusty--ubuntu_trusty&version=10.0)

**Comment by harshadyeola** [comment]
Looks like MariaDB has changed its repositories. 
https://downloads.mariadb.org/mariadb/repositories/#mirror=mephi&distro=Ubuntu&distro_release=trusty--ubuntu_trusty&version=10.0
We will release a fix for it soon.

**Comment by harshadyeola** [comment]
I think the problem is resolved now. Looks like it took time to sync repository packages for mariadb.
So I am closing this issue. Please feel free to reopen this issue if anyone face same problem again.

```
vagrant@vagrant-ubuntu-trusty-64:~$ lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:    14.04
Codename:    trusty
vagrant@vagrant-ubuntu-trusty-64:~$ sudo ee stack install --mysql
Adding repository for MySQL, please wait...
Updating apt-cache, please wait...
Installing packages, please wait...
Downloading MySQLTuner           [Done]
Reload : mysql     [OK]
Successfully installed packages
```

**Comment by ldashdixon** [comment]
Looks like the issue persists.  I've tried reinstalling easy engine, I've tried manually removing the mariadb repository and updating it all to no avail.   I'm still seeing the same error.  Perhaps you all haven't gone live with the fix yet?

**Comment by BenKnigge** [comment]
I just encountered this error today while trying to install.

**Comment by ldashdixon** [comment]
Just a heads up, it seems this issue has popped back up.  Can we expect this to happen every time mariadb updates?

**Comment by pvaladez** [comment]
I see the same issue with Debian 7.9 (wheezy) and EasyEngine v3.3.10.  Updating the "# MySQL repo and packages" section of /usr/local/lib/python3.4/dist-packages/ee-3.3.8-py3.4.egg/ee/core/variables.py as colthreepv suggests fixed my issue.  The default repo, http://mirror.aarnet.edu.au/, seems not to have the right file for Debian Wheezy.  Replacing this repo with http://mirrors.accretive-networks.net/mariadb/repo/10.0 worked for me.
